general {
    gaps_in = 5
    gaps_out = 15
    border_size = 3
    col.active_border = rgba(556b6bff) 45deg
    col.inactive_border = rgba(1c2828aa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2
    active_opacity = 0.9
    inactive_opacity = 0.8
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
    blur {
        enabled = true
        size = 2
        passes = 0
        vibrancy = 0.1696
    }
}

animations {
    enabled = yes

    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = softSnap, 0.2, 0.7, 0.1, 1.05
    bezier = linear, 0, 0, 1, 1

    animation = windows, 1, 3, softSnap, slide      # Появление окон со скольжением
    animation = windowsOut, 1, 3, easeOutExpo, popin 80% # Исчезновение чуть быстрее
    animation = windowsMove, 1, 3, easeOutExpo      # Перемещение окон

    animation = layers, 1, 2, easeOutExpo, fade

    animation = fade, 1, 3, easeOutExpo

    animation = border, 1, 5, linear
    animation = borderangle, 1, 30, linear, loop


    animation = workspaces, 1, 4, easeOutExpo, slidefade 20%
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
