$terminal = kitty
$fileManager = thunar
$menu = rofi -show run
$browser = firefox

exec-once = waybar
exec-once = awww-daemon
exec-once = awww img ~/.config/hypr/wallpaper/bg1.gif
exec-once = firefox 
exec-once = prizrak-box
exec-once = mako
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

